import { access, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { OpenApiDocument, OpenApiOperation, OpenApiSchema } from "./openapi";

const outputDir = fileURLToPath(new URL("../../../docs/api/", import.meta.url));
const operationsDir = join(outputDir, "operations");
const openApiJsonPath = join(outputDir, "openapi.json");
const openApiMarkdownPath = join(outputDir, "openapi.md");
const checkOnly = process.argv.includes("--check");

const httpMethods = new Set(["get", "post", "put", "patch", "delete", "options", "head"]);

type GeneratedArtifact = {
  relativePath: string;
  content: string;
};

function escapeMarkdown(value: string | undefined): string {
  return (value ?? "-").replaceAll("|", "\\|").replaceAll("\n", " ").trim();
}

function operationSlug(method: string, path: string): string {
  const pathSlug = path
    .replaceAll("{", "")
    .replaceAll("}", "")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  return `${method}-${pathSlug || "root"}`;
}

function schemaLabel(schema: OpenApiSchema | undefined): string {
  if (!schema) return "-";
  if (schema.$ref) return schema.$ref.replace("#/components/schemas/", "");
  if (schema.oneOf) return schema.oneOf.map(schemaLabel).join(" | ");
  if (schema.type === "array") return `array<${schemaLabel(schema.items)}>`;
  if (schema.enum) return schema.enum.map((item) => `"${item}"`).join(" | ");
  return schema.type ?? "object";
}

function requestSchemaLabel(operation: OpenApiOperation): string {
  const schema = operation.requestBody?.content["application/json"]?.schema;
  return schemaLabel(schema);
}

function responseSchemaLabel(operation: OpenApiOperation): string {
  const successResponse = operation.responses["200"] ?? operation.responses["201"];
  const schema = successResponse?.content?.["application/json"]?.schema;
  return schemaLabel(schema);
}

function operationEntries(api: OpenApiDocument): Array<{
  method: string;
  path: string;
  operation: OpenApiOperation;
  relativePath: string;
}> {
  const entries: Array<{
    method: string;
    path: string;
    operation: OpenApiOperation;
    relativePath: string;
  }> = [];
  for (const [path, pathItem] of Object.entries(api.paths).sort(([a], [b]) => a.localeCompare(b))) {
    for (const [method, operation] of Object.entries(pathItem)) {
      if (!httpMethods.has(method) || !operation) continue;
      entries.push({
        method,
        path,
        operation,
        relativePath: `operations/${operationSlug(method, path)}.md`
      });
    }
  }
  return entries;
}

function renderIndexMarkdown(api: OpenApiDocument): string {
  const lines = [
    `# ${api.info.title}`,
    "",
    "<!-- This file is generated by npm run docs:api. Do not edit manually. -->",
    "",
    `OpenAPI: \`${api.openapi}\``,
    `Version: \`${api.info.version}\``,
    "",
    api.info.description,
    "",
    "## Operations",
    "",
    "| Method | Path | Summary | Request | Success response | Detail |",
    "| --- | --- | --- | --- | --- | --- |",
    ...operationEntries(api).map(({ method, path, operation, relativePath }) =>
      `| \`${method.toUpperCase()}\` | \`${path}\` | ${escapeMarkdown(operation.summary)} | \`${escapeMarkdown(requestSchemaLabel(operation))}\` | \`${escapeMarkdown(responseSchemaLabel(operation))}\` | [詳細](${relativePath}) |`
    ),
    "",
    "## Schemas",
    "",
    "| Schema | Type | Required fields |",
    "| --- | --- | --- |",
    ...Object.entries(api.components.schemas)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([name, schema]) => `| \`${name}\` | \`${escapeMarkdown(schemaLabel(schema))}\` | ${escapeMarkdown(schema.required?.join(", ") || "-")} |`)
  ];
  return `${lines.join("\n")}\n`;
}

function renderOperationMarkdown(method: string, path: string, operation: OpenApiOperation): string {
  const lines = [
    `# ${method.toUpperCase()} ${path}`,
    "",
    "<!-- This file is generated by npm run docs:api. Do not edit manually. -->",
    "",
    "[API 一覧へ戻る](../openapi.md)",
    "",
    `Summary: ${operation.summary}`,
    "",
    operation.description ?? "-",
    "",
    "## Parameters",
    "",
    "| Name | In | Required | Type | Description |",
    "| --- | --- | --- | --- | --- |",
    ...(operation.parameters ?? []).map((parameter) =>
      `| \`${parameter.name}\` | \`${parameter.in}\` | ${parameter.required ? "yes" : "no"} | \`${escapeMarkdown(schemaLabel(parameter.schema))}\` | ${escapeMarkdown(parameter.description)} |`
    ),
    ...(operation.parameters?.length ? [] : ["| - | - | - | - | - |"]),
    "",
    "## Request Body",
    "",
    `- Required: ${operation.requestBody?.required ? "yes" : "no"}`,
    `- Schema: \`${requestSchemaLabel(operation)}\``,
    "",
    "## Responses",
    "",
    "| Status | Description | Schema |",
    "| --- | --- | --- |",
    ...Object.entries(operation.responses).map(([status, response]) =>
      `| \`${status}\` | ${escapeMarkdown(response.description)} | \`${escapeMarkdown(schemaLabel(response.content?.["application/json"]?.schema))}\` |`
    )
  ];
  return `${lines.join("\n")}\n`;
}

function renderArtifacts(api: OpenApiDocument): GeneratedArtifact[] {
  const json = `${JSON.stringify(api, null, 2)}\n`;
  return [
    { relativePath: "openapi.json", content: json },
    { relativePath: "openapi.md", content: renderIndexMarkdown(api) },
    ...operationEntries(api).map(({ method, path, operation, relativePath }) => ({
      relativePath,
      content: renderOperationMarkdown(method, path, operation)
    }))
  ];
}

function validateApi(api: OpenApiDocument): string[] {
  const errors: string[] = [];
  if (api.openapi !== "3.1.0") errors.push("OpenAPI version must be 3.1.0");
  if (!api.info.title) errors.push("info.title is required");
  for (const { method, path, operation } of operationEntries(api)) {
    if (!operation.summary) errors.push(`${method.toUpperCase()} ${path}: summary is required`);
    if (Object.keys(operation.responses).length === 0) errors.push(`${method.toUpperCase()} ${path}: responses are required`);
  }
  return errors;
}

async function loadRuntimeOpenApiDocument(): Promise<OpenApiDocument> {
  const { createApp } = await import("./app.js");
  const response = await createApp().request("/api/openapi.json");
  if (!response.ok) {
    throw new Error(`Failed to load OpenAPI document: ${response.status}`);
  }
  return await response.json() as OpenApiDocument;
}

async function checkArtifacts(artifacts: GeneratedArtifact[]): Promise<string[]> {
  const errors: string[] = [];
  const expectedPaths = new Set(artifacts.map((artifact) => artifact.relativePath));
  for (const artifact of artifacts) {
    const filePath = join(outputDir, artifact.relativePath);
    let current: string;
    try {
      current = await readFile(filePath, "utf8");
    } catch {
      errors.push(`${artifact.relativePath}: generated API docs do not exist. Run npm run docs:api.`);
      continue;
    }
    if (current !== artifact.content) {
      errors.push(`${artifact.relativePath}: generated API docs are out of date. Run npm run docs:api.`);
    }
  }
  try {
    const files = await readdir(operationsDir);
    for (const file of files.filter((item) => item.endsWith(".md"))) {
      const relativePath = `operations/${file}`;
      if (!expectedPaths.has(relativePath)) {
        errors.push(`${relativePath}: stale generated operation docs. Run npm run docs:api.`);
      }
    }
  } catch {
    errors.push("operations/: generated operation docs directory does not exist. Run npm run docs:api.");
  }
  return errors;
}

async function writeArtifacts(artifacts: GeneratedArtifact[]): Promise<void> {
  await mkdir(outputDir, { recursive: true });
  await rm(operationsDir, { recursive: true, force: true });
  await mkdir(operationsDir, { recursive: true });
  for (const artifact of artifacts) {
    await writeFile(join(outputDir, artifact.relativePath), artifact.content);
  }
}

async function main(): Promise<void> {
  const api = await loadRuntimeOpenApiDocument();
  const errors = validateApi(api);
  const artifacts = renderArtifacts(api);

  if (checkOnly) {
    errors.push(...await checkArtifacts(artifacts));
  }

  if (errors.length > 0) {
    console.error("API docs check failed:");
    for (const error of errors) console.error(`- ${error}`);
    process.exitCode = 1;
    return;
  }

  if (checkOnly) {
    console.log("API docs are up to date.");
    return;
  }

  await writeArtifacts(artifacts);
  console.log(`Generated ${openApiJsonPath}`);
  console.log(`Generated ${openApiMarkdownPath}`);
  console.log(`Generated ${operationsDir}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
